spring.application.name=jwtlogin

server.port=9999

logging.level.root=WARN
logging.level.com.sinse.jwtlogin.controller=DEBUG
logging.level.com.sinse.jwtlogin.model=DEBUG
## logging.level.org.springframework.security=DEBUG

spring.datasource.url=jdbc:mysql://localhost:3306/electroshop
spring.datasource.username=shop2
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.generate-ddl=false
spring.jpa.show-sql=true